DELETE TABLE BOARDS;

CREATE TABLE BOARDS (
    BOARD_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(256) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    READ_CNT NUMBER,
    CONTENT CLOB,
    REG_DATE DATE,
    UPDATE_DATE DATE
);

CREATE SEQUENCE BOARDS_SEQ;

SELECT * FROM BOARDS;


DELETE TABLE ATTACHMENTS;

CREATE TABLE ATTACHMENTS(
	ATTACHMENT_ID NUMBER PRIMARY KEY,
	FILE_NAME VARCHAR2(256),
	LOCATION VARCHAR2(1024),
	BOARD_ID NUMBER,
	REG_DATE DATE,
	CONSTRAINT F_ATTACHMENTS_BOARD FOREIGN KEY(BOARD_ID)
	REFERENCES BOARDS(BOARD_ID)
);

CREATE SEQUENCE ATTACHMENTS_SEQ;

SELECT * FROM ATTACHMENTS;

CREATE TABLE AVATAS(
	user_id VARCHAR2(20) PRIMARY KEY,
	image BLOB
);

select * from avatas;

CREATE TABLE REPLIES( 
	REPLY_ID NUMBER PRIMARY KEY, 
	BOARD_ID NUMBER, REPLY_LEVEL NUMBER, 
	PARENT NUMBER, 
	WRITER VARCHAR2(20) NOT NULL, 
	CONTENT VARCHAR2(1024), 
	DELETED NUMBER(1), 
	REG_DATE DATE, 
	UPDATE_DATE DATE, 
	CONSTRAINT F_REPLIES_BOARD FOREIGN KEY(BOARD_ID) REFERENCES BOARDS(BOARD_ID), 
	CONSTRAINT F_REPLIES_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBERS(USER_ID) 
);

select * from replies;

CREATE SEQUENCE REPLIES_SEQ;